# SettingsYaml settings file
#temperatureLimit: 85 #Max temperature limit
#minPowerLimit: 2 #Min TDP value
#maxPowerLimit: 30 #Max TDP Value
#powerLimitChangeStep: 2 #Value to increment or decrement from current TDP

#General Settings
delay: 1000 #Loop delay in milliseconds
experimental: true #true - does not make changes in system unless enabled from foreign source, useful with unstable values

#General CPU CU Settings
curveOptimizerChangeStep: 1 #Value to increment or decrement from current Curve Optimizer
curveOptimizerType: 0 #0 for All CPU CU, 1 for Per Core CPU CU

#For All CPU CU Settings
maxAllCoreCurveOptimizer: 5 #Max Curve Optimizer value
minAllCoreCurveOptimizer: 0 #Min Curve Optimizer value

#Per Core CPU CU Settings
perCoreCurveOptimizerCoreCount: 4 #Number of CPU Cores to apply CU
perCoreCurveOptimizerSets:
  - id: 0
    min: 0
    max: 5
  - id: 1
    min: 0
    max: 5
  - id: 2
    min: 0
    max: 5
  - id: 3
    min: 0
    max: 5







